MiniStoreProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/urls.py
from django.urls import path

from .views import (
    IndexView,
    ShopView,
    CartView,
    AddToCartView,
    RemoveFromCartView,CheckoutView,
    SignupView,
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,RedirectToIndexView,
    ActivateAccountView,ContactView,BlogView,ThankYouView,ContactSuccessView
)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('cart/', CartView.as_view(), name='cart'),
  #  path('<slug:category_slug>/', ShopView.as_view(), name='product-list-by-category'),
    path('add-to-cart/<int:product_id>/', AddToCartView.as_view(), name='add-to-cart'),
    path('remove-from-cart/<int:cart_item_id>/', RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('thankyou/', ThankYouView.as_view(), name='thankyou'),
    path('redirect-to-index/', RedirectToIndexView.as_view(), name='redirect-to-index'),
    
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/contact-success/', ContactSuccessView.as_view(), name='contact-success'),
    path('blog/', BlogView.as_view(), name='blog'), 

    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', PasswordChangeView.as_view(), name='password-change'),
    path('password-change/done/', PasswordResetDoneView.as_view(), name='password-change-done'),
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('activate/<str:uidb64>/<str:token>/', ActivateAccountView.as_view(), name='activate'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify

class BaseModel(models.Model):
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Category(BaseModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Product(BaseModel):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class CartItem(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name} (${self.product.price})"

class BlogPost(BaseModel):
    title = models.CharField(max_length=255)
    content = models.TextField()
    date_published = models.DateField()
    category = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class Testimonial(BaseModel):
    quote = models.TextField()
    rating = models.FloatField()
    author_name = models.CharField(max_length=255)

    def __str__(self):
        return self.author_name

class Order(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Order {self.id}"

    def total_quantity(self):
        return sum(item.quantity for item in self.order_items.all())

    def total_price(self):
        return sum(item.product.price * item.quantity for item in self.order_items.all())

class OrderItem(BaseModel):
    order = models.ForeignKey(Order, related_name='order_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"OrderItem {self.id} ({self.quantity} x {self.product.name})"

class Contact(BaseModel):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import CartItem,Contact



class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}))
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        labels = {
            'username': 'Username',
            'email': 'Email',
            'password1': 'Password',
            'password2': 'Confirm Password',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm your password'}),
        }
class CustomAuthenticationForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        super().confirm_login_allowed(user)

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'email', 'message']

class RemoveFromCartForm(forms.Form):
    product_id = forms.IntegerField(widget=forms.HiddenInput())



class AddToCartForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ['quantity']
        widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'form-control', 'min': 1, 'initial': 1})
        }

app/templates/activation_email.html
Click the link below to activate your account:

{{ protocol }}://{{ domain }}{% url 'activate' uidb64=uid token=token %}

app/templates/add_to_cart.html
<!-- templates/store/addtocart.html -->

{% load static %}
{% include "header.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add to Cart</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/addtocart.css' %}">
</head>
<body>

  <div class="content-box">
    {% block content %}
      <h1>Add {{ product.name }} to Cart</h1>
    
      <div class="card mb-4 box-shadow">
        <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
        <div class="card-body">
          <h3>{{ product.name }}</h3>
          <p class="card-text">{{ product.description }}</p>
          <p class="card-text">${{ product.price }}</p>
          
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add to Cart</button>
          </form>
          
          <a href="{% url 'shop' %}">Back to Products</a>
        </div>
      </div>
    {% endblock %}
  </div>
  
  <!-- Add your additional HTML or styling here -->

</body>
</html>

{% include "footer.html" %}

app/templates/cart.html
<!-- templates/store/cart.html -->

{% load static %}
{% include "header.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shopping Cart</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cart_style.css' %}">
    <!-- Add your additional CSS links here -->
    
</head>
<body>

  <div class="content-box">
    <h1>Your Shopping Cart</h1>

    {% block title %}Shopping Cart{% endblock %}

    {% block content %}
      {% if cart_items %}
        <table class="table">
          <thead>
            <tr>
              <th>Product Name</th>
              <th>Price</th>
              <th>Quantity</th>
              <th>Total</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for item in cart_items %}
                <tr>
                    <td>{{ item.product.name }}</td>
                    <td>${{ item.product.price }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>${{ item.total_price }}</td>
                    <td>
                        <form action="{% url 'remove-from-cart' item.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        </table>

        <!-- Checkout Button -->
        <a href="{% url 'checkout' %}" class="btn btn-primary checkout-btn">Checkout</a>

      {% else %}
        <p>Your cart is empty.</p>
      {% endif %}
      
      <div class="custom-links" style="margin-top: 20px;">
        <a href="{% url 'shop' %}" class="home-link">
          <i class="fas fa-home"></i> Go to Home
        </a>
      </div>
    {% endblock %}
  </div>
  
  <!-- Add your additional HTML or styling here -->

</body>
</html>

{% include "footer.html" %}

app/templates/checkout.html
<!-- templates/store/checkout.html -->

{% load static %}
{% include "header.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Shop</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/checkout_style.css' %}">
    <!-- Add your additional CSS links here -->
</head>

<body>

  <div class="content-box">
    <h1>Checkout</h1>

    {% block title %}Checkout{% endblock %}

    {% block content %}
      {% if cart_items %}
        <!-- Your existing table and checkout form logic -->
        <table class="table">
          <thead>
            <tr>
              <th>Product Name</th>
              <th>Price</th>
              <th>Quantity</th>
            </tr>
          </thead>
          <tbody>
            {% for item in cart_items %}
              <tr>
                <td>{{ item.product.name }}</td>
                <td>${{ item.product.price }}</td>
                <td>{{ item.quantity }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

        <!-- Display total price for all products -->
        <p class="total-price" style="font-weight: bold; color: green;">Total Price: ${{ total_price }}</p>

        {% if user.is_authenticated %}
          <a href="{% url 'thankyou' %}" class="btn btn-primary confirm-btn">Confirm Booking</a>
        {% else %}
          <p>Please <a href="{% url 'login' %}">log in</a> to confirm your booking.</p>
        {% endif %}
      {% else %}
        <p>Your cart is empty.</p>
      {% endif %}
      
      <div class="button-container" style="margin-top: 20px;">
        <a href="{% url 'shop' %}" class="btn btn-secondary">Home</a>
        <a href="{% url 'cart' %}" class="btn btn-secondary">Cart</a>
      </div>
      
    {% endblock %}
  </div>

  <!-- Add your additional HTML or styling here -->

</body>
</html>

{% include "footer.html" %}

app/templates/contact.html
{% load static %}
{% include "header.html" %}


    <!-- Start Hero Section -->
    <div class="hero" style="margin-top: 60px; padding-bottom: 30px;">
                <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-5">
                    <div class="intro-excerpt">
                        <h1>Contact Us</h1>
                        <p class="mb-4"></p>
                       
                    </div>
                </div>
                <div class="col-lg-7">

                </div>
            </div>
        </div>
    </div>
    <!-- End Hero Section -->

<!-- Start Contact Form -->
<div class="untree_co-section" style="margin-bottom: 80px;">
        <div class="container">
        <div class="block">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card mt-5">
                        <div class="card-body">
                            <h2 class="text-center mb-4">Contact Us</h2>
                            <form method="post" class="contact-form" id="contactForm">
                                {% csrf_token %}
                            
                                <div class="mb-3 row">
                                    <label for="id_first_name" class="form-label col-sm-2">
                                        First Name
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="Enter your First Name" required>
                                        {{ form.first_name.errors }}
                                    </div>
                                </div>                         
                            
                                <div class="mb-3 row">
                                    <label for="id_last_name" class="form-label col-sm-2">
                                        Last Name
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Enter your last name" required>
                                        {{ form.last_name.errors }}
                                    </div>
                                </div>                              
                            
                                <div class="mb-3 row">
                                    <label for="id_email" class="form-label col-sm-2">
                                        Email
                                    </label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id_email" name="email" placeholder="Enter your email" required>
                                        {{ form.email.errors }}
                                    </div>
                                </div>
                            
                                <div class="mb-3">
                                    <label for="id_message" class="form-label">Message</label>
                                    {{ form.message }}
                                </div>
                            
                                <div class="form-group mb-3 text-center">
                                    <button type="submit" class="btn btn-primary">Send Message</button>
                                </div>
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Contact Form -->

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/additional-methods.min.js"></script>

<script>
    $(document).ready(function () {
      $("#contactForm").validate({
        rules: {
          first_name: {
            required: true,
            minlength: 3,
          },
          last_name: {
            required: true,
            minlength: 3,
          },
          email: {
            required: true,
            email: true,
          },
          // Add rules for other form fields if needed
        },
        messages: {
          first_name: {
            required: "Please enter your first name",
            minlength: "Name should be at least 3 characters",
          },
          last_name: {
            required: "Please enter your last name",
            minlength: "Name should be at least 3 characters",
          },
          email: {
            required: "Please enter your email address",
            email: "Please enter a valid email address",
          },
          // Add messages for other form fields if needed
        },
        errorElement: "div",
        errorPlacement: function (error, element) {
          error.addClass("invalid-feedback");
          element.closest(".mb-3").append(error);
        },
        highlight: function (element, errorClass, validClass) {
          $(element).addClass("is-invalid").removeClass("is-valid");
        },
        unhighlight: function (element, errorClass, validClass) {
          $(element).addClass("is-valid").removeClass("is-invalid");
        },
      });
    });
  </script>




<style>
    /* Additional CSS for Contact Page */
    .hero {
        background-color: #f8f9fa;
        padding: 60px 0;
    }

    .intro-excerpt {
        max-width: 500px;
    }

    .contact-form {
        margin-top: 30px;
    }

    .card {
        border: none;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    }

    .card-body {
        padding: 30px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 15px 30px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }
</style>
    <!-- End Footer Section -->

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/tiny-slider.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

app/templates/contact_success.html
{% load static %}
{% include "header.html" %}
    <!-- Start Hero Section -->
    <div class="hero">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-5">
                    <div class="intro-excerpt">
                        <h1>Thank You Our team will contact you soon</h1>                     
                        <p><a href="{% url "index" %}" class="btn btn-secondary me-2">Back to homepage</a></p>
                    </div>
                </div>
                <div class="col-lg-7">

                </div>
            </div>
        </div>
    </div>
    <!-- End Hero Section -->                   
    <!-- Start Footer Section -->
    <footer class="footer-section">
        <div class="container relative">
            <div class="row">
                <div class="col-lg-8">
                    <div class="subscription-form">
                    </div>
                </div>
            </div>

            <div class="row g-5 mb-5">
                <div class="col-lg-4">

                </div>

                <div class="col-lg-8">
                    <div class="row links-wrap">
                        <div class="col-6 col-sm-6 col-md-3">
                            <ul class="list-unstyled">
                            </ul>
                        </div>
                    </div>
                </div>

            </div>

            <div class="border-top copyright">
                <div class="row pt-4">
                    <div class="col-lg-6">
                        <p class="mb-2 text-center text-lg-start">Copyright &copy;<script>document.write(new
                                Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by
                            <a href="https://untree.co">Untree.co</a> Distributed By <a
                                href="https://themewagon.com">ThemeWagon</a> <!-- License information:
                            https://untree.co/license/ -->
                        </p>
                    </div>

                    <div class="col-lg-6 text-center text-lg-end">
                        <ul class="list-unstyled d-inline-flex ms-auto">
                            <li class="me-4"><a href="#">Terms &amp; Conditions</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>

                </div>
            </div>

        </div>
        
        <script>
           
            Toastify({
                text: "Successfull",
                duration: 3000,
                gravity: "bottom", 
                position: "right", 
                offset: {
                    x: 50, 
                    y: 10  
                },
                style: {
                    background: "linear-gradient(to right, #ff9900, #ff0000)", 
                },
                onClick: function() {
                    
                }
            }).showToast();
             
        </script>
    </footer>
    <!-- End Footer Section -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/tiny-slider.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

app/templates/footer.html
{% load static %}
<footer id="footer" class="overflow-hidden">
    <div class="container">
      <div class="row">
        <div class="footer-top-area">
          <div class="row d-flex flex-wrap justify-content-between">
            <div class="col-lg-3 col-sm-6 pb-3">
              <div class="footer-menu">            
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>
  </footer>
  <div id="footer-bottom">
    <div class="container">
      <div class="row d-flex flex-wrap justify-content-between">
        <div class="col-md-4 col-sm-6">
          <div class="Shipping d-flex">
            <p>We ship with:</p>
            <div class="card-wrap ps-2">
             <img src="{% static 'images/dhl.png' %}"  alt="visa">
             <img src="{% static 'images/shippingcard.png' %}"  alt="mastercard">
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-6">
          <div class="payment-method d-flex">
            <p>Payment options:</p>
            <div class="card-wrap ps-2">
             <img src="{% static 'images/visa.jpg' %}"  alt="visa">
             <img src="{% static 'images/mastercard.jpg' %}"  alt="mastercard">
             <img src="{% static 'images/paypal.jpg' %}"  alt="paypal">
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-6">
          <div class="copyright">
            <p>© Copyright 2023 MiniStore. Design by <a href="https://templatesjungle.com/">TemplatesJungle</a> Distribution by <a href="https://themewagon.com">ThemeWagon</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>

  <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/plugins.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
  
</body>
</html>

app/templates/shop.html
{% load static %}
{% include "header.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Shop</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Add your additional CSS links here -->

    <!-- Add Bootstrap CSS link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Custom CSS to move the product section down -->
    <style>
        body {
            padding-top: 90px; /* Adjust the value as needed */
        }

        .category-container {
            margin-top: 60px; /* Add margin to separate the categories */
            margin-bottom: 120px; /* Adjust the margin-bottom to move the footer down */
        }

        .product-card {
            margin-bottom: 90px;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="category-container">
            <h1 class="my-4">Mobile Phones</h1>
    
            <div class="row">
                {% for product in category_one_products %}
                    <div class="col-md-4">
                        <div class="card product-card">
                            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.description }}</p>
                                <p class="card-text">${{ product.price }}</p>
                                <a href="{% url 'add-to-cart' product.id %}" class="btn btn-primary">Add to Cart</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
    
                <!-- Pagination controls for category_one_products -->
                <div class="pagination">
                    <span class="step-links">
                        {% if category_one_products.has_previous %}
                            <a href="?page_one=1">&laquo; first</a>
                            <a href="?page_one={{ category_one_products.previous_page_number }}">previous</a>
                        {% endif %}
    
                        <span class="current">
                            Page {{ category_one_products.number }} of {{ category_one_products.paginator.num_pages }}.
                        </span>
    
                        {% if category_one_products.has_next %}
                            <a href="?page_one={{ category_one_products.next_page_number }}">next</a>
                            <a href="?page_one={{ category_one_products.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    
        <!-- Repeat the same structure for the second category -->
        <div class="category-container">
            <h1 class="my-4">Smart Watches</h1>
    
            <div class="row">
                {% for product in category_two_products %}
                    <div class="col-md-4">
                        <div class="card product-card">
                            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.description }}</p>
                                <p class="card-text">${{ product.price }}</p>
                                <a href="{% url 'add-to-cart' product.id %}" class="btn btn-primary">Add to Cart</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
    
                 <!-- Pagination controls for category_two_products -->
            <div class="pagination">
                <span class="step-links">
                    {% if category_two_products.has_previous %}
                        <a href="?page_two=1">&laquo; first</a>
                        <a href="?page_two={{ category_two_products.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ category_two_products.number }} of {{ category_two_products.paginator.num_pages }}.
                    </span>

                    {% if category_two_products.has_next %}
                        <a href="?page_two={{ category_two_products.next_page_number }}">next</a>
                        <a href="?page_two={{ category_two_products.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>

{% include "footer.html" %}

<!-- Add Bootstrap JS and jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

app/templates/thankyou.html
{% load static %}
{% include "header.html" %}

{% block title %}Thank You{% endblock %}

{% block content %}
  <div style="padding-top: 50px; padding-bottom: 50px;">
    <h1>Thank You!</h1>
    <p>Your order has been confirmed.</p>
    
    <h2>Your Last Order Details:</h2>
    
    {% if order %}
        <p>Order ID: {{ order.id }}</p>
        <p>Total Quantity: {{ order.total_quantity }}</p>
        <p>Total Price: ${{ order.total_price }}</p>
        <!-- Add more order details here as needed -->
    {% else %}
        <p>No orders found.</p>
    {% endif %}
    
    <button onclick="window.location.href='{% url 'shop' %}'">Continue Shopping</button>
  </div>
{% endblock %}

{% include "footer.html" %}


    <!-- <h2>Order Details:</h2>
    {% if cart_items %}
     
      <table class="table">
        <thead>
          <tr>
            <th>Product Name</th>
            <th>Price</th>
            <th>Quantity</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart_items %}
            <tr>
              <td>{{ item.product.name }}</td>
              <td>${{ item.product.price }}</td>
              <td>{{ item.quantity }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

     
      <p class="total-price" style="font-weight: bold; color: green;">Total Price: ${{ total_price }}</p>
    {% else %}
      <p>No items in the order.</p>
    {% endif %} 
  
     class ThankYouView(TemplateView):
    template_name = 'thankyou.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        cart_items = CartItem.objects.all()  
        total_price = sum(item.product.price * item.quantity for item in cart_items)  

        context['cart_items'] = cart_items
        context['total_price'] = total_price
    
        return context
-->

   